# 第2章 Pythonの基本

## 2.1 四則演算

### 2.1.1 四則演算の利用

In [1]:
1 + 2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

### 2.1.2 累乗

In [3]:
2 ** 8

256

## 2.2 変数

### 2.2.1 変数を利用した計算

In [4]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

### 2.2.2 変数名の表記

In [5]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

### 2.2.3 複数の変数を1行で定義

In [6]:
a, b, c = 100, 200, 300
a + b + c

600

## 2.3 型

### 2.3.1 型の種類

### 2.3.2 型の調査

In [7]:
type(100)

int

In [8]:
type(100.1)

float

In [9]:
x = 100
type(x)

int

In [10]:
x = 100.1
type(x)

float

### 2.3.3 文字列

In [11]:
x = "learning"
type(x)

str

## 2.4 print文

### 2.4.1 print文の利用

In [12]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [13]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


### 2.4.2 文字列と組み合わせた数値の表示1

In [14]:
x = 1 / 3
y = 2 / 3
print("x=", x, ", y=", y)

x= 0.3333333333333333 , y= 0.6666666666666666


### 2.4.3 文字列と組み合わせた数値の表示2

In [15]:
x = 1 / 3
y = 2 / 3
print(f"x= {x}, y= {y}")

x= 0.3333333333333333, y= 0.6666666666666666


In [16]:
x = 1 / 3
y = 2 / 3
print(f"x= {x:.2f}, y= {y:.2f}")

x= 0.33, y= 0.67


## 2.5 list（リスト、配列変数）

### 2.5.1 listの利用

In [17]:
x = [1, 2, 3, 4, 5]  # list の定義
print(x)             # 表示

[1, 2, 3, 4, 5]


In [18]:
x[0]

1

In [19]:
x[2]

3

In [20]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [21]:
s = ["SUN", 1, "MON", 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [22]:
x = [1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [23]:
x = [1, 1, 2, 3, 5]
len(x)

5

### 2.5.2 2次元の配列

In [24]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [26]:
a = [[1, 2, 3], [4, 5, 6]]
print(a[0][1])
print(type(a[0]))

2
<class 'list'>


### 2.5.3 連続した整数の配列の作成

In [28]:
y = range(5)
print(y[0], y[1], y[2], y[3], y[4])
print(type(y))

0 1 2 3 4
<class 'range'>


In [29]:
print(y)

range(0, 5)


In [30]:
z = list(range(5))
print(z)

[0, 1, 2, 3, 4]


In [31]:
list(range(5, 10))

[5, 6, 7, 8, 9]

## 2.6 tuple（タプル）

### 2.6.1 tupleの利用

In [32]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


### 2.6.2 要素の参照

In [33]:
a = (1, 2, 3)
a[1]

2

In [34]:
type(a)

tuple

### 2.6.3 長さが1のtuple

In [35]:
a = (1)
type(a)

int

In [36]:
a = (1,)
type(a)

tuple

## 2.7 if文

### 2.7.1 if文の利用

In [38]:
x = 9
if x > 10:
    print("x is ")                    # ... (A1)
    print("        larger than 10.")  # ... (A2)
else:
    print("x is smaller than 11")     # ... (B1)

x is smaller than 11


In [39]:
x > 10

False

In [40]:
type(x > 10)

bool

### 2.7.2 比較演算子

In [41]:
x = 15
if 10 < x and x < 20:
    print("x is between 10 and 20.")

x is between 10 and 20.


## 2.8 for文

### 2.8.1 for文の利用

In [42]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [44]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):  # len(num) は num の要素数
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


### 2.8.2 enumerateの利用

In [45]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 2.9 ベクトル

In [46]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### 2.9.1 NumPyの利用

In [47]:
import numpy as np

### 2.9.2 ベクトルの定義

In [50]:
x = np.array([1, 2])
x

y = [1,2]

In [52]:
print(x)
print(y)
print(type(x))
print(type(y))

[1 2]
[1, 2]
<class 'numpy.ndarray'>
<class 'list'>


In [53]:
x = np.array([1, 2])
y = np.array([3, 4])
print(x + y)

[4 6]


In [54]:
type(x)

numpy.ndarray

### 2.9.3 要素の参照

In [55]:
x = np.array([1, 2])
print(x[0])

1


### 2.9.4 要素の書き換え

In [56]:
x = np.array([1, 2])
x[0] = 100
print(x)

[100   2]


### 2.9.5 連続した整数のベクトルの作成

In [57]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [58]:
print(np.arange(5, 10))

[5 6 7 8 9]


### 2.9.6 ndarray 型の注意点

In [59]:
a = np.array([1, 1])
b = a
print("a =", a)
print("b =", b)
b[0] = 100
print("b =", b)
print("a =", a)

a = [1 1]
b = [1 1]
b = [100   1]
a = [100   1]


In [60]:
a = np.array([1, 1])
b = a.copy()
print("a =", a)
print("b =", b)
b[0] = 100
print("b =", b)
print("a =", a)

a = [1 1]
b = [1 1]
b = [100   1]
a = [1 1]


### 2.9.7 要素がランダムな値のベクトルの生成

In [66]:
np.random.rand()

0.8195371761542091

In [67]:
for i in range(3):
    print(np.random.rand())

0.2072849516754417
0.6000256859570436
0.5390124499307093


In [73]:
np.random.seed(seed=1)
for i in range(3):
    print(np.random.rand())

0.417022004702574
0.7203244934421581
0.00011437481734488664


In [75]:
np.random.seed(seed=1)
data = np.random.rand(1)
print(np.round(data, 2))

[0.42]


## 2.10 行列

### 2.10.1 行列の定義

In [76]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


### 2.10.2 行列のサイズ

In [79]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [80]:
h, w = x.shape
print(h)
print(w)

2
3


In [81]:
w = x.shape[1]
print(w)

3


### 2.10.3 要素の参照

In [82]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2]

6

### 2.10.4 要素の書き換え

In [83]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


### 2.10.5 要素が0や1のndarrayの作成

In [84]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [85]:
x = np.zeros((2, 10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [86]:
x = np.ones((2, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 2.10.6 行列のサイズの変更

In [87]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [107]:
a = a.reshape(1, 10)
print(a)

[[0 1 2 3 4 5 6 7 8 9]]


In [99]:
b = a.reshape(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [108]:
c = a.reshape(-1)
print(c)

[0 1 2 3 4 5 6 7 8 9]


### 2.10.7 行列やベクトルの連結

In [109]:
x0 = np.array([[1, 2], [3, 4]])
print(x0)
x1 = np.array([[100, 200], [300, 400]])
print(x1)

[[1 2]
 [3 4]]
[[100 200]
 [300 400]]


In [101]:
y = np.c_[x0, x1]
print(y)

[[  1   2 100 200]
 [  3   4 300 400]]


In [102]:
y = np.r_[x0, x1]
print(y)

[[  1   2]
 [  3   4]
 [100 200]
 [300 400]]


In [103]:
v0 = np.array([1, 2, 3])
v1 = np.array([100, 200, 300])
z = np.c_[v0, v1]
print(z)

[[  1 100]
 [  2 200]
 [  3 300]]


## 2.11 行列の演算

### 2.11.1 行列における四則演算

In [1]:
import numpy as np

x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


### 2.11.2 スカラー × 行列

In [2]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


### 2.11.3 算術関数

In [ ]:
x = np.array([[4, 4, 4], [9, 9, 9]])
print(np.sqrt(x))

### 2.11.4 行列積の計算

In [3]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v @ w)

[[14 14]
 [32 32]]


## 2.12 スライシング

In [4]:
import numpy as np

x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [5]:
print(x[5:])

[5 6 7 8 9]


In [6]:
print(x[3:8])

[3 4 5 6 7]


In [7]:
print(x[3:8:2])

[3 5 7]


In [10]:
print(x[::-3])

[9 6 3 0]


In [ ]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[:2, 1:2])

## 2.13 条件を満たすデータの書き換え

In [ ]:
import numpy as np

x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

In [ ]:
x[x > 3]

In [ ]:
x[x > 3] = 999
print(x)

## 2.14 Help

In [ ]:
import numpy as np

help(np.random.randint)

## 2.15 関数

### 2.15.1 関数の利用

In [ ]:
def my_func1():
    print("Hi!")
    
# 関数 my_func1() の定義はここまで

my_func1()  # 関数を実行

In [12]:
def my_func2(a, b):
    c = a + b
    return c

A = my_func2(1, 2) + 3
print(A)

6


### 2.15.2 引数と戻り値

In [ ]:
import numpy as np

def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [ ]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print(f"mean:{data_mean:.2f}, std:{data_std:.2f}")

In [ ]:
output = my_func3(data)
print(output)
print(type(output))
print(f"mean:{output[0]:.2f}, std:{output[1]:.2f}")

### 2.15.3 位置引数とキーワード引数

In [ ]:
def my_func4(alpha, beta, gamma):  # 関数定義
    print(f"ALPHA={alpha}, BETA={beta}, GAMMA={gamma}")

my_func4(1, 2, 3)  # 関数実行

In [ ]:
my_func4(beta=2, alpha=1, gamma=3)

In [ ]:
my_func4(1, gamma=3, beta=2)

### 2.15.4 ローカル変数

In [ ]:
def add_10(x):
    y = x + 10
    print(f"local: x = {x}, y = {y}")

add_10(1000)

In [ ]:
x = 1
y = 2
add_10(1000)                        # (A)
print(f"global: x = {x}, y = {y}")  # (B)


## 2.16 ファイル保存

### 2.16.1 1つのndarray型の保存

In [ ]:
import numpy as np

data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

np.save("datafile.npy", data)   # ファイル保存
data = np.array([])             # データの消去
print(data)

data = np.load("datafile.npy")  # ファイル読み出し
print(data)

In [13]:
import numpy as np

data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

np.save("dataf")

[ 1  1  2  3  5  8 13]


### 2.16.2 複数のndarray型の保存

In [14]:
x0 = np.array([1, 2, 3])
x1 = np.array([10, 20, 30])
np.savez("datafile2.npz", x0=x0, x1=x1)  # ファイル保存
x0 = np.array([])                        # x0の消去
x1 = np.array([])                        # x1の消去
data = np.load("datafile2.npz")  # (A) ファイル読み出し
print(data.files)                # 格納している全変数名の表示
x0 = data["x0"]                  # x0の取り出し
x1 = data["x1"]                  # x1の取り出し
print(x0)
print(x1)

['x0', 'x1']
[1 2 3]
[10 20 30]
